# Generated by Django 3.0.6 on 2020-06-28 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('surname', models.CharField(default='', max_length=255, verbose_name='Détail')),
                ('agemin', models.IntegerField(verbose_name='Age min.')),
                ('agemax', models.IntegerField(verbose_name='Age max.')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'db_table': 'agecategory',
                'ordering': ['agemin', 'gender', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('isteam', models.BooleanField(default=False, verbose_name='Equipe')),
                ('ismasters', models.BooleanField(default=False, verbose_name='Masters')),
                ('isminime', models.BooleanField(default=False, verbose_name='Minime')),
                ('place', models.CharField(max_length=255, verbose_name='Lieu')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('troop', models.IntegerField(verbose_name='Nombre de participants max')),
                ('countevents', models.IntegerField(default=0, verbose_name='Nombre de participants inscrits')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('closed', models.BooleanField(default=False, verbose_name='Clos')),
            ],
            options={
                'verbose_name': 'Compétition',
                'db_table': 'competition',
            },
        ),
        migrations.CreateModel(
            name='Concurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ffhmfacUser', models.IntegerField(null=True, unique=True)),
                ('ffhmfacClub', models.IntegerField(null=True)),
                ('clubName', models.CharField(max_length=255, null=True)),
                ('licence', models.CharField(max_length=255, null=True)),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Athlète',
                'db_table': 'concurrent',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('verbosename', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Genre',
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Leadertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'leadertype',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('preseason_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Saison',
                'db_table': 'season',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Weightcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.CharField(max_length=5, verbose_name='Poids en kg')),
                ('agecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agecategory', verbose_name="catégorie d'âge")),
            ],
            options={
                'verbose_name': 'Catégories de poids',
                'verbose_name_plural': 'Catégories de poids',
                'db_table': 'weightcategory',
                'ordering': ['id', 'agecategory', 'weight'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('draw', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Competition')),
            ],
            options={
                'verbose_name': 'Equipe',
                'db_table': 'team',
                'ordering': ['draw'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('licence', models.CharField(blank=True, max_length=255, null=True)),
                ('club', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Minimumweightcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('weight', models.IntegerField(verbose_name='Poids en kg')),
                ('weightcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Weightcategory', verbose_name='minima')),
            ],
            options={
                'verbose_name': 'Minimun par catégories de poids',
                'db_table': 'minimumweightcategory',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Competition')),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Concurrent')),
                ('leadertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Leadertype')),
            ],
            options={
                'verbose_name': 'Dirigeant',
                'db_table': 'leader',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ffhmfacClub', models.IntegerField(null=True)),
                ('clubName', models.CharField(max_length=255, null=True)),
                ('draw', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.IntegerField(default=0)),
                ('iwf', models.FloatField(default=0)),
                ('agecategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Agecategory')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Competition')),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Concurrent')),
                ('minimumweightcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Minimumweightcategory')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Team')),
                ('weightcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Weightcategory')),
            ],
            options={
                'verbose_name': 'Evènement',
                'db_table': 'event',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='concurrent',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gender'),
        ),
        migrations.CreateModel(
            name='Competitionkind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gender')),
            ],
            options={
                'verbose_name': 'Type de compétition',
                'db_table': 'competitionkind',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gender', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='competition',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Season', verbose_name='Saison'),
        ),
        migrations.AddField(
            model_name='competition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=0)),
                ('validate', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
            ],
            options={
                'verbose_name': 'Tentative',
                'db_table': 'attempt',
                'ordering': ['name', 'rank'],
            },
        ),
        migrations.AddField(
            model_name='agecategory',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gender', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='agecategory',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Season', verbose_name='Saison'),
        ),
    ]
