# Generated by Django 3.0.8 on 2020-10-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='view_order',
            field=models.IntegerField(default=0),
        ),
    ]
