# Generated by Django 3.0.8 on 2020-10-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_leader_view_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='view_order',
        ),
        migrations.AddField(
            model_name='leadertype',
            name='view_order',
            field=models.IntegerField(default=0),
        ),
    ]
