# Generated by Django 3.0.8 on 2022-01-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionkind',
            name='gender',
        ),
        migrations.AddField(
            model_name='competition',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Competitionkind', verbose_name='Type'),
        ),
    ]
