# Generated by Django 3.0.8 on 2023-01-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220123_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionkind',
            options={'ordering': ['name'], 'verbose_name': 'Type de compétition'},
        ),
        migrations.AddField(
            model_name='competition',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Visibilité'),
        ),
    ]
