# Generated by Django 5.2.3 on 2025-07-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_wallpaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallpaper',
            old_name='Wallpaper',
            new_name='wallpaper',
        ),
    ]
