# Generated by Django 5.2.3 on 2025-07-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_wallpaper_wallpaper_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
