# Generated by Django 5.2.3 on 2025-10-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_wallpaper_is_active_alter_wallpaper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='isrecordeligible',
            field=models.BooleanField(default=False, verbose_name='Eligible aux records'),
        ),
    ]
