# Generated by Django 5.2.3 on 2025-10-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_competition_isrecordeligible'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arr', models.IntegerField(default=0)),
                ('ep_j', models.IntegerField(default=0)),
                ('weightcategory', models.CharField(max_length=5)),
                ('agecategory', models.CharField(choices=[('SENIORS', 'SENIORS'), ('U15', 'U15'), ('U17', 'U17'), ('U20', 'U20')], max_length=7)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gender', verbose_name='Genre')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season', verbose_name='Saison')),
            ],
            options={
                'verbose_name': 'Standards Record de France',
                'db_table': 'record_standard',
            },
        ),
    ]
