# Generated by Django 5.2.3 on 2025-10-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_recordstandard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordstandard',
            options={'verbose_name': 'Standard Record de France', 'verbose_name_plural': 'Standards Record de France'},
        ),
        migrations.AlterField(
            model_name='agecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='competitionkind',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='concurrent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadertype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='minimumweightcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recordstandard',
            name='agecategory',
            field=models.CharField(choices=[('SENIORS', 'SENIORS'), ('U15', 'U15'), ('U17', 'U17'), ('U20', 'U20')], max_length=7, verbose_name="Catégorie d'âge"),
        ),
        migrations.AlterField(
            model_name='recordstandard',
            name='arr',
            field=models.IntegerField(default=0, verbose_name='Arraché'),
        ),
        migrations.AlterField(
            model_name='recordstandard',
            name='ep_j',
            field=models.IntegerField(default=0, verbose_name='Epaulé jeté'),
        ),
        migrations.AlterField(
            model_name='recordstandard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recordstandard',
            name='weightcategory',
            field=models.CharField(max_length=5, verbose_name='Catégorie de poids de corps'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weightcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arr', models.BooleanField(default=False, verbose_name='Arraché')),
                ('ep_j', models.BooleanField(default=False, verbose_name='Epaulé jeté')),
                ('total', models.BooleanField(default=False, verbose_name='Total')),
                ('is_current', models.BooleanField(default=False, verbose_name='Record en cours')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
            options={
                'verbose_name': 'Record de France',
                'verbose_name_plural': 'Records de France',
                'db_table': 'record',
            },
        ),
    ]
