# Generated by Django 5.2.3 on 2025-10-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_recordstandard_options_alter_agecategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordstandard',
            name='agecategory',
            field=models.CharField(choices=[('SENIOR', 'SENIOR'), ('U15', 'U15'), ('U17', 'U17'), ('U20', 'U20')], max_length=7, verbose_name="Catégorie d'âge"),
        ),
    ]
