# Generated by Django 5.2.3 on 2025-12-16 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_recordstandard_agecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='event',
            field=models.ForeignKey(limit_choices_to={'competition__isrecordeligible': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
