# Generated by Django 5.2.3 on 2025-12-17 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_record_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='agecategory',
            field=models.CharField(blank=True, choices=[('SENIOR', 'SENIOR'), ('U20', 'U20'), ('U15', 'U15'), ('U17', 'U17')], max_length=7, null=True, verbose_name="Catégorie d'âge"),
        ),
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gender', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='record',
            name='kind',
            field=models.CharField(blank=True, choices=[('ARR', 'ARR'), ('EP-J', 'EP-J'), ('TOTAL', 'TOTAL')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='weightcategory',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Catégorie de poids de corps'),
        ),
        migrations.AlterField(
            model_name='recordstandard',
            name='agecategory',
            field=models.CharField(choices=[('SENIOR', 'SENIOR'), ('U20', 'U20'), ('U15', 'U15'), ('U17', 'U17')], max_length=7, verbose_name="Catégorie d'âge"),
        ),
    ]
