# Generated by Django 5.2.3 on 2025-12-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_record_agecategory_record_gender_record_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
