# Generated by Django 5.2.3 on 2025-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_record_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='arr',
        ),
        migrations.RemoveField(
            model_name='record',
            name='ep_j',
        ),
        migrations.RemoveField(
            model_name='record',
            name='total',
        ),
        migrations.AlterField(
            model_name='record',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
